### ISSUE TITLE
Search pagination issues

### ISSUE THREAD

**Issue by josielewis-warren** [FutureNorthants/northants-website#42]
**Frontend or Backend**: Design System

**Description**
When you search and go to page 2 or 3 of results, then refine and do a new search, it'll give you new results but send you straight to page 2 or 3 of those new results rather than page 1.

**How to reproduce**

Browser: Edge 

**Additional context**

Originally recorded on the bug tracker by Steven Miller 19/05/21 - confirmed still an issue 17/06/21

**Comment by josielewis-warren** [comment]
Potential Design system issue

**Comment by apricot13** [comment]
all the management for the url's are in `/src/helpers/url-helpers.js`  https://github.com/FutureNorthants/northants-design-system/blob/master/src/library/helpers/url-helpers.js

when you're working with this stuff on the design system you'll need to comment out line 19 `uri.setPath(`/${postTo}`);` otherwise the redirects will fail. (remember to put it back before you commit your code!)

**Comment by AnthonyTaylor** [comment]
Investigation - 6hrs
Work - 2hrs- 6hrs
Test - 1hr
9-13hrs
